package ba.fluxor.fetchapi.feature.tabs.ui.request

import androidx.compose.foundation.layout.*
import androidx.compose.material3.Checkbox
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import ba.fluxor.fetchapi.component.KeyValueDescTable
import ba.fluxor.fetchapi.feature.request.data.KeyValueEntry
import fetchapi.composeapp.generated.resources.Res
import fetchapi.composeapp.generated.resources.headers
import fetchapi.composeapp.generated.resources.hide_auto_generated
import org.jetbrains.compose.resources.stringResource

@Composable
fun HeadersSection(
  headers: List<KeyValueEntry>,
  autoGenerated: List<KeyValueEntry>,
  onChange: (List<KeyValueEntry>) -> Unit,
) {
  var hideAuto by remember { mutableStateOf(false) }

  Column(modifier = Modifier.fillMaxWidth()) {
    Row(
      verticalAlignment = Alignment.CenterVertically,
      modifier = Modifier.fillMaxWidth().padding(bottom = 4.dp),
    ) {
      Spacer(Modifier.weight(1f))
      Checkbox(checked = hideAuto, onCheckedChange = { hideAuto = it })
      Text(
        text = stringResource(Res.string.hide_auto_generated),
        color = MaterialTheme.colorScheme.onSurface,
      )
    }
    KeyValueDescTable(
      rows = headers,
      onChange = onChange,
      modifier = Modifier.fillMaxWidth(),
      readOnlyRows = if (hideAuto) emptyList() else autoGenerated,
      keyPlaceholder = stringResource(Res.string.headers),
    )
  }
}
