package ba.fluxor.fetchapi.feature.tabs.ui.request

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import ba.fluxor.fetchapi.component.KeyValueDescTable
import ba.fluxor.fetchapi.feature.request.data.KeyValueEntry
import fetchapi.composeapp.generated.resources.Res
import fetchapi.composeapp.generated.resources.headers
import org.jetbrains.compose.resources.stringResource

@Composable
fun HeadersSection(
  headers: List<KeyValueEntry>,
  autoGenerated: List<KeyValueEntry>,
  onChange: (List<KeyValueEntry>) -> Unit,
) {
  var hideAuto by remember { mutableStateOf(false) }

  Column(modifier = Modifier.fillMaxWidth()) {
    KeyValueDescTable(
      rows = headers,
      onChange = onChange,
      modifier = Modifier.fillMaxWidth(),
      readOnlyRows = if (hideAuto) emptyList() else autoGenerated,
      keyPlaceholder = stringResource(Res.string.headers),
      onHideAutoGeneratedRows = { hideAuto = !hideAuto },
    )
  }
}
