package ba.fluxor.fetchapi.feature.tabs.ui

import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.Divider
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import ba.fluxor.fetchapi.component.CompactInput
import ba.fluxor.fetchapi.component.SimpleDropdown
import ba.fluxor.fetchapi.component.SquareButton
import ba.fluxor.fetchapi.component.SquareOutlineButton
import ba.fluxor.fetchapi.feature.tabs.ui.request.BodySection
import ba.fluxor.fetchapi.feature.tabs.ui.request.HeadersSection
import ba.fluxor.fetchapi.feature.tabs.ui.request.ParamsSection
import ba.fluxor.fetchapi.feature.tabs.ui.request.RequestAuthorizationSection
import ba.fluxor.fetchapi.feature.tabs.ui.request.UrlParamSync
import ba.fluxor.fetchapi.feature.tabs.ui.request.computeAutoHeaders
import ba.fluxor.fetchapi.feature.tabs.viewmodel.RequestTab
import ba.fluxor.fetchapi.feature.tabs.viewmodel.TabBuffer
import ba.fluxor.fetchapi.network.http.HttpMethod
import fetchapi.composeapp.generated.resources.*
import org.jetbrains.compose.resources.stringResource

@Composable
fun RequestTabEditor(
  buffer: TabBuffer.Request,
  isDirty: Boolean,
  onChange: (TabBuffer) -> Unit,
  onSave: () -> Unit,
) {
  var selectedTab by remember { mutableStateOf(RequestTab.entries.first()) }

  Column(modifier = Modifier.fillMaxSize().padding(16.dp)) {

    Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) {
      CompactInput(
        value = buffer.name,
        onValueChange = { onChange(buffer.copy(name = it)) },
      )
      Spacer(Modifier.weight(1f))
      SquareButton(
        text = stringResource(Res.string.save),
        onClick = onSave,
        enabled = isDirty,
        modifier = Modifier
          .background(MaterialTheme.colorScheme.tertiary)
          .padding(horizontal = 16.dp, vertical = 6.dp),
      )
    }
    Spacer(Modifier.height(12.dp))
    Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) {
      SimpleDropdown(
        options = HttpMethod.entries.map { it.name },
        selected = buffer.method,
        onSelect = { onChange(buffer.copy(method = it)) },
        width = 100.dp,
        optionLabel = { it },
      )
      Spacer(Modifier.width(8.dp))
      CompactInput(
        value = buffer.url,
        onValueChange = { newUrl ->
          val newParams = UrlParamSync.mergeFromUrl(newUrl, buffer.params)
          onChange(buffer.copy(url = newUrl, params = newParams))
        },
        placeholder = stringResource(Res.string.url),
        modifier = Modifier.weight(1f),
      )
      Spacer(Modifier.width(8.dp))
      SquareButton(
        text = stringResource(Res.string.send),
        onClick = {},
        modifier = Modifier.padding(horizontal = 16.dp, vertical = 6.dp),
      )
    }

    Spacer(Modifier.height(12.dp))
    Divider(thickness = 1.dp)
    Spacer(Modifier.height(12.dp))

    Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) {
      RequestTab.entries.forEach { tab ->
        SquareOutlineButton(
          text = stringResource(tab.labelRes()),
          onClick = { selectedTab = tab },
          modifier = Modifier.padding(horizontal = 16.dp),
          borderWidth = if (selectedTab == tab) 2.dp else 0.dp,
        )
      }
    }
    Spacer(Modifier.height(8.dp))
    Divider(thickness = 1.dp)
    Spacer(Modifier.height(16.dp))

    Box(modifier = Modifier.weight(1f, fill = false).fillMaxWidth()) {
      when (selectedTab) {
        RequestTab.PARAMS -> ParamsSection(
          params = buffer.params,
          onChange = { newParams ->
            val newUrl = UrlParamSync.rebuildUrl(buffer.url, newParams)
            onChange(buffer.copy(params = newParams, url = newUrl))
          },
        )
        RequestTab.AUTHORIZATION -> RequestAuthorizationSection(
          authType = buffer.authType,
          authConfig = buffer.authConfig,
          onChange = { newType, newConfig ->
            onChange(buffer.copy(authType = newType, authConfig = newConfig))
          },
        )
        RequestTab.HEADERS -> HeadersSection(
          headers = buffer.headers,
          autoGenerated = computeAutoHeaders(buffer),
          onChange = { newHeaders -> onChange(buffer.copy(headers = newHeaders)) },
        )
        RequestTab.BODY -> BodySection(
          body = buffer.body,
          onChange = { newBody -> onChange(buffer.copy(body = newBody)) },
        )
      }
    }

    Spacer(Modifier.height(16.dp))

    val scrollState = rememberScrollState()
    val shape = RoundedCornerShape(4.dp)

    SelectionContainer(
      modifier = Modifier.border(1.dp, MaterialTheme.colorScheme.primary, shape = shape),
    ) {
      BasicTextField(
        value = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a",
        onValueChange = {},
        readOnly = true,
        modifier = Modifier
          .heightIn(min = 200.dp, max = 400.dp)
          .fillMaxWidth()
          .padding(12.dp)
          .verticalScroll(scrollState)
          .horizontalScroll(rememberScrollState()),
        textStyle = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 14.sp),
      )
    }
  }
}
